### ISSUE TITLE
github project parking?

### ISSUE THREAD

**Issue by arboreal84** [jhermsmeier/node-quic#1]
I have seen this with DNS but this takes it to the next level.

**Comment by jhermsmeier** [comment]
I've only seen this now, as I'm starting to work on it again (and I never saw a notification about this)... Could you elaborate on why having a repository sitting around is next level name parking?

I think you might have confused this with the published [quic package on npm](https://www.npmjs.com/package/quic) – that's not from me nor is it this repository – that's at [toajs/quic](https://github.com/toajs/quic).
